Repository clp-research/slurk, pull requests merged in 2019-03, with the labels that each got.

#44 Startup scripts
  tools/start_clients.py
  tools/start_server_and_bot.py
Labels: Area: Client, Category: Enhancement

#48 Turn-taking bot
  sample_bots/turntaking/questions_images.json
  sample_bots/turntaking/turntaking_bot.py
Labels: Status: Awaiting feedback

#58 Add Description of how to build the docs to README
  README.md
  docs/slurk_installation.rst
Labels: Area: Documentation, Category: Enhancement, Status: In Progress

#65 Create CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: Area: Documentation

#62 Documentation for Quickstart, Pairing up, and Layouts and Plugins
  docs/slurk_layouts.rst
  docs/slurk_multibots.rst
  docs/slurk_quickstart.rst
  docs/slurk_taskroom.png
  docs/slurk_waitingroom.png
Labels: Area: Documentation

#60 Version 1.1: Layout and Plugins
  CHANGELOG.md
Labels: Area: Deployment, Priority: Critical, Status: Awaiting feedback
